language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t gagaception/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true gagaception/docker-react yarn test